repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/networknt/pre-commit-hook-keyword
    rev: 516ca4cdd10570254f670d0553aaa72f9bb64da7
    hooks:
    -   id: keywordscan
        args: ["--keywords=abcdef,xyzuvw,opqrst"]
        types: ["text"]
